apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokube
spec:
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      labels:
        app: hellokube
    spec:
      containers:
      - name: my-lovely-pi
        image: quay.io/manue/hellopy:latest
        ports:
        - containerPort: 5000
