apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: give-me-a-persistent-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: sef
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
