apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: give-me-a-persistent-volume
  namespace: hello
spec:
  storageClassName: "ocs-storagecluster-cephfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  
