apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "update to container V3, with requests and limits"
      labels:
        app: hellokube
    spec:
      containers:
      - name: my-lovely-pi
        image: quay.io/manue/hellopy:2
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hellokube
spec:
  selector:
    app: hellokube
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: hellokube
spec:
  port:
    targetPort: 8080
  to:
    kind: ""
    name: hellokube
    weight: null
status: {}
