apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "update to container V2, with liveness probe"
      labels:
        app: hellokube
    spec:
      containers:
      - name: my-lovely-pi
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        image: quay.io/manue/hellopy:2
        ports:
        - containerPort: 8080
