apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "update to container V4, with volumeMount"
      labels:
        app: hellokube
    spec:
      containers:
      - name: my-lovely-pi
        image: quay.io/manue/hellopy:2
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: oida-my-volume-storage
          mountPath: /var/oida-my-container-storage
      volumes:
      - name: oida-my-volume-storage
        persistentVolumeClaim:
          claimName: give-me-a-persistent-volume
---
apiVersion: v1
kind: Service
metadata:
  name: hellokube
spec:
  selector:
    app: hellokube
  ports:
  - port: 8080
    targetPort: 8080
