apiVersion: v1
kind: Service
metadata:
  labels:
    app: hellokube
  name: hellokube
  namespace: hello
spec:
  ports:
  - name: 80-8080
    nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hellokube
  type: NodePort
