apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tested-storage
  namespace: hello
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
